### ISSUE TITLE
TCA changes in ext_tables.php

### ISSUE THREAD

**Issue by IchHabRecht** [einpraegsam/ipandlanguageredirect#10]
As I noticed, you change the TCA in your ext_tables.php file as you are using ExtensionUtility::registerPlugin and ExtensionManagementUtility::addStaticFile in here. The file is included in backend context only and both function calls should be move to (at least) one file in Configuration/TCA/Overrides

**Comment by einpraegsam** [comment]
Thx for your note. Interested in a PR?
