### ISSUE TITLE
Errors after including static template (TYPO3 7.6.31 + ipandlanguageredirect 1.7.2)

### ISSUE THREAD

**Issue by sheydin** [einpraegsam/ipandlanguageredirect#12]
Getting the following errors after including the static template:

Core: Error handler (FE): PHP Warning: include_once(/website/yellow-head/typo3_src-7.6.31/vendor/pear/pear_exception): failed to open stream: Success in /website/typo3conf/ext/ipandlanguageredirect/Classes/Utility/ConfigurationUtility.php line 20

Core: Error handler (FE): PHP Warning: include_once(): Failed opening '' for inclusion (include_path='/website/typo3_src-7.6.31/vendor/pear/pear_exception:/website/typo3_src-7.6.31/vendor/pear/http_request2:.:/usr/lib/php7.0') in /website/typo3conf/ext/ipandlanguageredirect/Classes/Utility/ConfigurationUtility.php line 20

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to In2code\Ipandlanguageredirect\Domain\Model\ConfigurationSet::__construct() must be of the type array, boolean given, called in /website/typo3_src-7.6.31/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4569 | TypeError thrown in file /website/typo3conf/ext/ipandlanguageredirect/Classes/Domain/Model/ConfigurationSet.php in line 39. Requested URL: https://website.de/?type=1555

Please help.

**Comment by einpraegsam** [comment]
For whatever reason the configuration could not be set on your instance. Pls check if your configuration path really exits (Extension Manager settings of ipandlanguageredirect).

**Comment by sheydin** [comment]
Thank you. It was the wrong path.
