### ISSUE TITLE
Make "alreadyRedirectedParameter" configurable?

### ISSUE THREAD

**Issue by koehnlein** [einpraegsam/ipandlanguageredirect#18]
I don't understand the benefit of `alreadyRedirectedParameter` which appends `r=1` to redirect URLs.

In my TYPO3 configuration, it's added to all canonical tags, language links, etc. where typolinks is configured to automatically add the current query string. I know I can search all these configurations and add `r` to exclude list. But I think, it would be much easier to not have this parameter added to the redirect URL at all.

A solution could be to remove it from javascript file and make make the parameters configurable via TypoScript for JSON backend?

**Comment by einpraegsam** [comment]
This is not at least a security feature to not loop a visitor on some strange configuration. If r is set, no more redirects will happen. At the moment it is not planned to remove this feature.
