### ISSUE TITLE
Google (Bot, Pagespeed, etc.) and other search engines following the IP redirect

### ISSUE THREAD

**Issue by bernhardberger** [einpraegsam/ipandlanguageredirect#19]
I've ran into an issue where google and co get redirected to my US version of the page. I however need it to stay at the default page..

Is there any option to block out user agents or sth similar?

**Comment by msollmann** [comment]
I can confirm this issue!

**Comment by einpraegsam** [comment]
Look at the example configuration how to exclude google bot from redirects https://github.com/einpraegsam/ipandlanguageredirect#example-configuration
