### ISSUE TITLE
Array output instead of page in Frontend

### ISSUE THREAD

**Issue by hilburger** [einpraegsam/ipandlanguageredirect#20]
Sometimes I get this in front-end instead of the rendered page: 

`{"redirectUri":"https:\/\/dev.website.local\/en\/all-information\/everything-about-your-journey\/","activated":true,"events":["suggest"],"activatedReasons":{"differentLanguages":true,"differentRootpages":false},"country":"","givenParameters":{"browserLanguage":"","referrer":"","ipAddress":"2a02:8108:50c0:5b1c:fd01:d3f0:91ff:3e5d","languageUid":0,"rootpageUid":1,"countryCodeOverlay":"","domain":"dev.website.local"}}`

Clearing the cache does not help and I have no idea what is wrong. 
Once this happens on a page I can't get it back to work.

TYPO3 8.7.20 LTS
On Debian PHP 7.0.33

**Comment by einpraegsam** [comment]
I can't reproduce this issue, sorry
