### ISSUE TITLE
Suggest message in redirect Language?

### ISSUE THREAD

**Issue by TimoWinkler** [einpraegsam/ipandlanguageredirect#21]
Shouldn't the suggest message be in the language that was detected instead of the language of the current site?

Having a message that the user should be able to read based on IP and Browser Language should be prefered over a language that the user might not be able to read at all.

**Comment by einpraegsam** [comment]
Yes, I know what you mean. Nevertheless the initial sponsort wanted to have this feature in exactly this behaviour. 
Nevertheless, maybe we will switch this in the future, because I have the same opinion.
