### ISSUE TITLE
Redirect only once

### ISSUE THREAD

**Issue by instruccionesaldorso** [einpraegsam/ipandlanguageredirect#22]
We tried your extension and it works great!
But we're experiencing an issue and we're not sure if this is the right behaviour or not.
The first time we tried to open the domain www.example.com in an incognito window, it redirects to the appropriate language version based on GeoIP (based in our configuration) (e.g. www.example.com/xx/?r=1), but next time we introduce the domain url www.example.com in the browser, it just goes to the default language.
Is this normal?
Is the behaviour only applied for the first time you access the domain?

**Comment by einpraegsam** [comment]
This is a wanted behaviour for this browser and session. When the visitor was redirected to the best fitting website-language version, a cookie is set (see the &r=1). If this cookie exists, there will not be a second redirect. 
If this feature would not work, it would not be possible for the user to manually switch to a wanted language version of the website (the extension would redirect him back).
