### ISSUE TITLE
User Default Language Cookie

### ISSUE THREAD

**Issue by Hadess1994** [einpraegsam/ipandlanguageredirect#29]
Hi,
the actual behavior is that when you don't show the banner and redirect automatically on the preferred language, there will be the cookie "ipandlanguageredirect_disableredirect" automatic set. That means, if the users opens the site in another tab there will be no more redirect.
Is it possible to include a cookie like "User Default Language Cookie" that evaluates which language the user should be redirected?

**Comment by einpraegsam** [comment]
This feature is not possible at the moment and there are no plans to add the current behaviour - sorry :)
