### ISSUE TITLE
Define extension key in its composer.json

### ISSUE THREAD

**Issue by instruccionesaldorso** [einpraegsam/ipandlanguageredirect#32]
The TYPO3 extension package "in2code/ipandlanguageredirect", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)

**Comment by einpraegsam** [comment]
Thx, will be fixed in 4.0.1
