### ISSUE TITLE
redirect all pages to english/L=1 if not de,ch,at

### ISSUE THREAD

**Issue by celmedia** [einpraegsam/ipandlanguageredirect#4]
i tryed to make the extension runing for the last 2 days on 8.7.3 ... but i cant get any results in the redirect ... can someone help please ... i also would pay for help. 

my redirect php is : 

return [
    'quantifier' => [
        'browserLanguage' => [
            'totalMatch' => 7,
            'wildCardMatch' => 3
        ],
        'countryBasedOnIp' => [
            'totalMatch' => 13,
            'wildCardMatch' => 5
        ],
        'actions' => [
            'referrers' => [
                'totalMatch' => 7,
                'wildCardMatch' => 3,
            ]
        ]
    ],
    'actions' => [
        [
            'referrers' => [
                'google.',
                'bing.',
                'yahoo.',
                't-online.',
                'yandex.',
                'baidu.',
                'links.playground.localhost.de',
            ],
            'events' => [
                'redirect'
            ]
        ],
        [
            'referrers' => [
                '*'
            ],
            'events' => [
                'suggest'
            ]
        ]
    ],
    'noMatchingConfiguration' => [
        'identifierUsage' => 'worldwide_english',
        'matchMinQuantifier' => 15
    ],
    'redirectConfiguration' => [
        // this number means: pid
        // Worldwide, Europe
        // Build URI to page 1 if visitors came from anywhere in the world
        1 => [        
	        // Build URI to language 0 if browser language is german "en"
            0 => [
                'identifier' => 'worldwide_german',
                'browserLanguage' => [
                    'de'
                ],
                'countryBasedOnIp' => [
                    'de',
                    'ch',
                    'at',
                ]
            ],	
	        // Build URI to language 1 if browser language is not defined here
            1 => [
                'identifier' => 'worldwide_english',
                'browserLanguage' => [
                    '*'
                ],
                'countryBasedOnIp' => [
                    '*',
                ]
            ],
            // Build URI to language 2 if browser language is chinese "fr"
            2 => [
                'identifier' => 'worldwide_france',
                'browserLanguage' => [
                    'fr'
                ],
                'countryBasedOnIp' => [
                    'fr'
                ]
            ],
        ],
    ]
];

if i check the domain over : 
https://typo3.cel.media/?type=1555

il get the output : 
{"redirectUri":"https:\/\/typo3.cel.media\/index.php?id=1&L=1","activated":true,"events":["suggest"],"activatedReasons":{"differentLanguages":true,"differentRootpages":false},"givenParameters":{"browserLanguage":"","referrer":"","ipAddress":"178.195.128.222","languageUid":0,"rootpageUid":1,"countryCodeOverlay":""}}

but if il check normaly over 
https://typo3.cel.media/
nothing happend there ... it should be https://typo3.cel.media/en

my language is L=0 is de    L=1 is en   L=2 is fr 

please someone help or know someone who can help with redirecting ... thanks

**Comment by einpraegsam** [comment]
If I open https://typo3.cel.media/ and do a quick look into browserconsole I see that the request from JS is answered with 303 from your server.
You can try it by yourself by opening the URL: https://typo3.cel.media/?type=1555&tx_ipandlanguageredirect_pi1[browserLanguage]=de&tx_ipandlanguageredirect_pi1[ipAddress]=null&tx_ipandlanguageredirect_pi1[referrer]=https://github.com/einpraegsam/ipandlanguageredirect/issues/4&tx_ipandlanguageredirect_pi1[languageUid]=0&tx_ipandlanguageredirect_pi1[rootpageUid]=1&tx_ipandlanguageredirect_pi1[countryCode]=
I think this is only a configuration issue.
