### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by nicolez9911** [einpraegsam/ipandlanguageredirect#9]
We installed the extension and it's working fine in chrome, firefox, safari and edge. But in IE11 the redirect is not working. Also the debug information (when opening the page with ipandlanguagedebug=1) is not complete. It just shows "ipandlanguageredirect debug activated" and nothing more.

**Comment by einpraegsam** [comment]
Checked in Browserstack, but can't see a problem in IE11
Are you interested in sponsoring or doing a pull request with a fix?

**Comment by einpraegsam** [comment]
ok, will close this issue because of missing feedback
